spring.application.name=knote
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.cache=false

knote.minio.host=${MINIO_HOST:localhost}
knote.minio.bucket=${MINIO_BUCKET:image-storage}
knote.minio.access.key=${MINIO_ACCESS_KEY:}
knote.minio.secret.key=${MINIO_SECRET_KEY:}
knote.minio.useSSL=${MINIO_USE_SSL:false}
knote.minio.reconnect.enabled=${MINIO_RECONNECT_ENABLED:true}
